FROM node:25

WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Define the command to run your app using CMD which defines your runtime
# Here, npm start is the typical command to start a Node.js/React/Vue app
CMD ["npm", "run", "dev"]
