/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreatePostInputType: { // input type
    authorId: string; // ID!
    body: string; // String!
    title: string; // String!
  }
  PostsInputType: { // input type
    published?: boolean | null; // Boolean
    search?: string | null; // String
  }
}

export interface NexusGenEnums {
  TaskStatus: "COMPLETED" | "IN_PROGRESS" | "NOT_STARTED" | "OVERACHIEVED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Cart: { // root type
    id: string; // ID!
    totalPrice: number; // Float!
  }
  CartItem: { // root type
    quantity: number; // Int!
  }
  Comment: { // root type
    body: string; // String!
    id: string; // ID!
  }
  Mutation: {};
  Post: { // root type
    body: string; // String!
    id: string; // ID!
    published: boolean; // Boolean!
    title: string; // String!
  }
  Product: { // root type
    description: string; // String!
    id: string; // ID!
    inStock?: boolean | null; // Boolean
    name: string; // String!
    price: number; // Int!
    tags: string[]; // [String!]!
  }
  Query: {};
  Task: { // root type
    actualPomodoros: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    estimatedPomodoros: number; // Int!
    id: string; // ID!
    isActive: boolean; // Boolean!
    isChecked: boolean; // Boolean!
    listName: string; // String!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // root type
    email: string; // String!
    id: string; // ID!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Cart: { // field return type
    id: string; // ID!
    items: NexusGenRootTypes['CartItem'][]; // [CartItem!]!
    totalPrice: number; // Float!
  }
  CartItem: { // field return type
    product: NexusGenRootTypes['Product'] | null; // Product
    quantity: number; // Int!
  }
  Comment: { // field return type
    author: NexusGenRootTypes['User']; // User!
    body: string; // String!
    id: string; // ID!
    post: NexusGenRootTypes['Post']; // Post!
  }
  Mutation: { // field return type
    addComment: NexusGenRootTypes['Comment']; // Comment!
    addItemToCart: NexusGenRootTypes['Cart']; // Cart!
    createCart: NexusGenRootTypes['Cart']; // Cart!
    createPost: NexusGenRootTypes['Post']; // Post!
    publishPost: NexusGenRootTypes['Post']; // Post!
    removeItemFromCart: NexusGenRootTypes['Cart']; // Cart!
    updateCartItem: NexusGenRootTypes['Cart']; // Cart!
  }
  Post: { // field return type
    author: NexusGenRootTypes['User']; // User!
    body: string; // String!
    comments: Array<NexusGenRootTypes['Comment'] | null>; // [Comment]!
    id: string; // ID!
    published: boolean; // Boolean!
    title: string; // String!
  }
  Product: { // field return type
    description: string; // String!
    id: string; // ID!
    inStock: boolean | null; // Boolean
    name: string; // String!
    price: number; // Int!
    tags: string[]; // [String!]!
  }
  Query: { // field return type
    cart: NexusGenRootTypes['Cart'] | null; // Cart
    post: NexusGenRootTypes['Post'] | null; // Post
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    product: NexusGenRootTypes['Product'] | null; // Product
    products: NexusGenRootTypes['Product'][]; // [Product!]!
    users: NexusGenRootTypes['User'][][] | null; // [[User!]!]
  }
  Task: { // field return type
    actualPomodoros: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    estimatedPomodoros: number; // Int!
    id: string; // ID!
    isActive: boolean; // Boolean!
    isChecked: boolean; // Boolean!
    listName: string; // String!
    status: NexusGenEnums['TaskStatus']; // TaskStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Cart: { // field return type name
    id: 'ID'
    items: 'CartItem'
    totalPrice: 'Float'
  }
  CartItem: { // field return type name
    product: 'Product'
    quantity: 'Int'
  }
  Comment: { // field return type name
    author: 'User'
    body: 'String'
    id: 'ID'
    post: 'Post'
  }
  Mutation: { // field return type name
    addComment: 'Comment'
    addItemToCart: 'Cart'
    createCart: 'Cart'
    createPost: 'Post'
    publishPost: 'Post'
    removeItemFromCart: 'Cart'
    updateCartItem: 'Cart'
  }
  Post: { // field return type name
    author: 'User'
    body: 'String'
    comments: 'Comment'
    id: 'ID'
    published: 'Boolean'
    title: 'String'
  }
  Product: { // field return type name
    description: 'String'
    id: 'ID'
    inStock: 'Boolean'
    name: 'String'
    price: 'Int'
    tags: 'String'
  }
  Query: { // field return type name
    cart: 'Cart'
    post: 'Post'
    posts: 'Post'
    product: 'Product'
    products: 'Product'
    users: 'User'
  }
  Task: { // field return type name
    actualPomodoros: 'Int'
    createdAt: 'DateTime'
    estimatedPomodoros: 'Int'
    id: 'ID'
    isActive: 'Boolean'
    isChecked: 'Boolean'
    listName: 'String'
    status: 'TaskStatus'
    title: 'String'
    updatedAt: 'DateTime'
  }
  User: { // field return type name
    email: 'String'
    id: 'ID'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Comment: {
    author: { // args
      id: string; // ID!
    }
    post: { // args
      id: string; // ID!
    }
  }
  Mutation: {
    addComment: { // args
      authorId: string; // ID!
      body: string; // String!
      postId: string; // ID!
    }
    addItemToCart: { // args
      cartId: string; // ID!
      productId: string; // ID!
      quantity: number; // Int!
    }
    createPost: { // args
      data?: NexusGenInputs['CreatePostInputType'] | null; // CreatePostInputType
    }
    publishPost: { // args
      id: string; // ID!
    }
    removeItemFromCart: { // args
      cartId: string; // ID!
      productId: string; // ID!
    }
    updateCartItem: { // args
      cartId: string; // ID!
      productId: string; // ID!
      quantity: number; // Int!
    }
  }
  Post: {
    author: { // args
      id: string; // ID!
    }
  }
  Query: {
    cart: { // args
      id: string; // ID!
    }
    post: { // args
      id: string; // ID!
    }
    posts: { // args
      data?: NexusGenInputs['PostsInputType'] | null; // PostsInputType
    }
    product: { // args
      id: string; // ID!
    }
    products: { // args
      maxPrice?: number | null; // Float
      minPrice?: number | null; // Float
      search?: string | null; // String
      tag?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}