/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { GraphQLContext } from "./src/api/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  SessionStatus: "END" | "PAUSE" | "PLAY" | "RUNNING"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  MusicTrack: { // root type
    artistName: string; // String!
    audioUrl: string; // String!
    coverImageUrl: string; // String!
    durationSeconds: number; // Int!
    id: string; // ID!
    isLoopable?: boolean | null; // Boolean
    title: string; // String!
  }
  Project: { // root type
    color: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId: string; // ID!
  }
  Query: {};
  Session: { // root type
    actualBreakTime: number; // Int!
    actualFocusTime: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    endedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    pausedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    sessionBreakTime: number; // Int!
    sessionCount: number; // Int!
    sessionFocusTime: number; // Int!
    sessionStatus: NexusGenEnums['SessionStatus']; // SessionStatus!
    userId: string; // ID!
  }
  Task: { // root type
    completed?: boolean | null; // Boolean
    completedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    currentCount?: number | null; // Int
    description: string; // String!
    estimatedCount?: number | null; // Int
    id: string; // ID!
    is_checked?: boolean | null; // Boolean
    projectId: string; // ID!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  User: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    id: string; // ID!
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserPrefs: { // root type
    breakTime: number; // Int!
    darkMode: boolean; // Boolean!
    focusTime: number; // Int!
    longBreakInterval: number; // Int!
    longBreakTime: number; // Int!
    userId: string; // ID!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  MusicTrack: { // field return type
    artistName: string; // String!
    audioUrl: string; // String!
    coverImageUrl: string; // String!
    durationSeconds: number; // Int!
    id: string; // ID!
    isLoopable: boolean | null; // Boolean
    title: string; // String!
  }
  Project: { // field return type
    color: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    userId: string; // ID!
  }
  Query: { // field return type
    activeTask: Array<NexusGenRootTypes['Task'] | null> | null; // [Task]
  }
  Session: { // field return type
    actualBreakTime: number; // Int!
    actualFocusTime: number; // Int!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    endedAt: NexusGenScalars['DateTime'] | null; // DateTime
    pausedAt: NexusGenScalars['DateTime'] | null; // DateTime
    sessionBreakTime: number; // Int!
    sessionCount: number; // Int!
    sessionFocusTime: number; // Int!
    sessionStatus: NexusGenEnums['SessionStatus']; // SessionStatus!
    userId: string; // ID!
  }
  Task: { // field return type
    completed: boolean | null; // Boolean
    completedAt: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    currentCount: number | null; // Int
    description: string; // String!
    estimatedCount: number | null; // Int
    id: string; // ID!
    is_checked: boolean | null; // Boolean
    projectId: string; // ID!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    id: string; // ID!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserPrefs: { // field return type
    breakTime: number; // Int!
    darkMode: boolean; // Boolean!
    focusTime: number; // Int!
    longBreakInterval: number; // Int!
    longBreakTime: number; // Int!
    userId: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  MusicTrack: { // field return type name
    artistName: 'String'
    audioUrl: 'String'
    coverImageUrl: 'String'
    durationSeconds: 'Int'
    id: 'ID'
    isLoopable: 'Boolean'
    title: 'String'
  }
  Project: { // field return type name
    color: 'String'
    createdAt: 'DateTime'
    description: 'String'
    id: 'ID'
    name: 'String'
    updatedAt: 'DateTime'
    userId: 'ID'
  }
  Query: { // field return type name
    activeTask: 'Task'
  }
  Session: { // field return type name
    actualBreakTime: 'Int'
    actualFocusTime: 'Int'
    createdAt: 'DateTime'
    endedAt: 'DateTime'
    pausedAt: 'DateTime'
    sessionBreakTime: 'Int'
    sessionCount: 'Int'
    sessionFocusTime: 'Int'
    sessionStatus: 'SessionStatus'
    userId: 'ID'
  }
  Task: { // field return type name
    completed: 'Boolean'
    completedAt: 'DateTime'
    createdAt: 'DateTime'
    currentCount: 'Int'
    description: 'String'
    estimatedCount: 'Int'
    id: 'ID'
    is_checked: 'Boolean'
    projectId: 'ID'
    updatedAt: 'DateTime'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'ID'
    name: 'String'
    updatedAt: 'DateTime'
  }
  UserPrefs: { // field return type name
    breakTime: 'Int'
    darkMode: 'Boolean'
    focusTime: 'Int'
    longBreakInterval: 'Int'
    longBreakTime: 'Int'
    userId: 'ID'
  }
}

export interface NexusGenArgTypes {
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: GraphQLContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}