/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { GraphQLContext } from "./src/api/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateProjectInput: { // input type
    color?: string | null; // String
    icon?: string | null; // String
    name: string; // String!
  }
  CreateTaskInput: { // input type
    notes?: string | null; // String
    project_id?: string | null; // ID
    sort_order?: number | null; // Int
    target_sessions?: number | null; // Int
    title: string; // String!
  }
  EndSessionInput: { // input type
    actual_duration_seconds?: number | null; // Int
    session_id: string; // ID!
    status?: string | null; // String
  }
  PauseSessionInput: { // input type
    session_id: string; // ID!
  }
  StartSessionInput: { // input type
    cycle_index?: number | null; // Int
    planned_duration_seconds: number; // Int!
    session_type: string; // String!
  }
  UpdatePomodoroPrefsInput: { // input type
    default_break_minutes?: number | null; // Int
    default_focus_minutes?: number | null; // Int
    default_long_break_minutes?: number | null; // Int
    long_break_every?: number | null; // Int
  }
  UpdateTasksCompletedSessionsInput: { // input type
    task_ids: string[]; // [ID!]!
  }
  UpdateTasksCompletionInput: { // input type
    is_completed: boolean; // Boolean!
    task_ids: string[]; // [ID!]!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Mutation: {};
  Project: { // root type
    color?: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    icon?: string | null; // String
    id: string; // ID!
    is_archived: boolean; // Boolean!
    name: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
    user_id: string; // ID!
  }
  Query: {};
  SessionInfo: { // root type
    actual_duration_seconds?: number | null; // Int
    created_at: NexusGenScalars['DateTime']; // DateTime!
    cycle_index?: number | null; // Int
    ended_at?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    planned_duration_seconds: number; // Int!
    session_type: string; // String!
    started_at: NexusGenScalars['DateTime']; // DateTime!
    status: string; // String!
    user_id: string; // ID!
  }
  SessionTask: { // root type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    seconds_spent?: number | null; // Int
    session_id: string; // ID!
    sort_order?: number | null; // Int
    task_id: string; // ID!
  }
  Task: { // root type
    completed_at?: NexusGenScalars['DateTime'] | null; // DateTime
    completed_sessions: number; // Int!
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: string; // ID!
    is_archived: boolean; // Boolean!
    is_completed: boolean; // Boolean!
    notes?: string | null; // String
    project_id?: string | null; // ID
    sort_order?: number | null; // Int
    target_sessions: number; // Int!
    title: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
    user_id: string; // ID!
  }
  User: { // root type
    avatar_url?: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    default_break_minutes: number; // Int!
    default_focus_minutes: number; // Int!
    default_long_break_minutes: number; // Int!
    display_name?: string | null; // String
    email: string; // String!
    id: string; // ID!
    long_break_every: number; // Int!
    timezone: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createProject: NexusGenRootTypes['Project']; // Project!
    createTask: NexusGenRootTypes['Task']; // Task!
    endSession: NexusGenRootTypes['SessionInfo']; // SessionInfo!
    pauseSession: NexusGenRootTypes['SessionInfo']; // SessionInfo!
    startSession: NexusGenRootTypes['SessionInfo']; // SessionInfo!
    updatePomodoroPrefs: NexusGenRootTypes['User']; // User!
    updateTasksCompletedSessions: NexusGenRootTypes['Task'][]; // [Task!]!
    updateTasksCompletion: NexusGenRootTypes['Task'][]; // [Task!]!
  }
  Project: { // field return type
    color: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    icon: string | null; // String
    id: string; // ID!
    is_archived: boolean; // Boolean!
    name: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
    user_id: string; // ID!
  }
  Query: { // field return type
    active_tasks: NexusGenRootTypes['Task'][]; // [Task!]!
    past_logs: NexusGenRootTypes['Task'][]; // [Task!]!
    projects: NexusGenRootTypes['Project'][]; // [Project!]!
    tasks: NexusGenRootTypes['Task'][]; // [Task!]!
    tasksByProjectId: NexusGenRootTypes['Task'][]; // [Task!]!
  }
  SessionInfo: { // field return type
    actual_duration_seconds: number | null; // Int
    created_at: NexusGenScalars['DateTime']; // DateTime!
    cycle_index: number | null; // Int
    ended_at: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    planned_duration_seconds: number; // Int!
    session_type: string; // String!
    started_at: NexusGenScalars['DateTime']; // DateTime!
    status: string; // String!
    user_id: string; // ID!
  }
  SessionTask: { // field return type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    seconds_spent: number | null; // Int
    session_id: string; // ID!
    sort_order: number | null; // Int
    task_id: string; // ID!
  }
  Task: { // field return type
    completed_at: NexusGenScalars['DateTime'] | null; // DateTime
    completed_sessions: number; // Int!
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: string; // ID!
    is_archived: boolean; // Boolean!
    is_completed: boolean; // Boolean!
    notes: string | null; // String
    project: NexusGenRootTypes['Project'] | null; // Project
    project_id: string | null; // ID
    sort_order: number | null; // Int
    target_sessions: number; // Int!
    title: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
    user_id: string; // ID!
  }
  User: { // field return type
    avatar_url: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    default_break_minutes: number; // Int!
    default_focus_minutes: number; // Int!
    default_long_break_minutes: number; // Int!
    display_name: string | null; // String
    email: string; // String!
    id: string; // ID!
    long_break_every: number; // Int!
    timezone: string; // String!
    updated_at: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createProject: 'Project'
    createTask: 'Task'
    endSession: 'SessionInfo'
    pauseSession: 'SessionInfo'
    startSession: 'SessionInfo'
    updatePomodoroPrefs: 'User'
    updateTasksCompletedSessions: 'Task'
    updateTasksCompletion: 'Task'
  }
  Project: { // field return type name
    color: 'String'
    created_at: 'DateTime'
    icon: 'String'
    id: 'ID'
    is_archived: 'Boolean'
    name: 'String'
    updated_at: 'DateTime'
    user_id: 'ID'
  }
  Query: { // field return type name
    active_tasks: 'Task'
    past_logs: 'Task'
    projects: 'Project'
    tasks: 'Task'
    tasksByProjectId: 'Task'
  }
  SessionInfo: { // field return type name
    actual_duration_seconds: 'Int'
    created_at: 'DateTime'
    cycle_index: 'Int'
    ended_at: 'DateTime'
    id: 'ID'
    planned_duration_seconds: 'Int'
    session_type: 'String'
    started_at: 'DateTime'
    status: 'String'
    user_id: 'ID'
  }
  SessionTask: { // field return type name
    created_at: 'DateTime'
    seconds_spent: 'Int'
    session_id: 'ID'
    sort_order: 'Int'
    task_id: 'ID'
  }
  Task: { // field return type name
    completed_at: 'DateTime'
    completed_sessions: 'Int'
    created_at: 'DateTime'
    id: 'ID'
    is_archived: 'Boolean'
    is_completed: 'Boolean'
    notes: 'String'
    project: 'Project'
    project_id: 'ID'
    sort_order: 'Int'
    target_sessions: 'Int'
    title: 'String'
    updated_at: 'DateTime'
    user_id: 'ID'
  }
  User: { // field return type name
    avatar_url: 'String'
    created_at: 'DateTime'
    default_break_minutes: 'Int'
    default_focus_minutes: 'Int'
    default_long_break_minutes: 'Int'
    display_name: 'String'
    email: 'String'
    id: 'ID'
    long_break_every: 'Int'
    timezone: 'String'
    updated_at: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createProject: { // args
      input: NexusGenInputs['CreateProjectInput']; // CreateProjectInput!
    }
    createTask: { // args
      input: NexusGenInputs['CreateTaskInput']; // CreateTaskInput!
    }
    endSession: { // args
      input: NexusGenInputs['EndSessionInput']; // EndSessionInput!
    }
    pauseSession: { // args
      input: NexusGenInputs['PauseSessionInput']; // PauseSessionInput!
    }
    startSession: { // args
      input: NexusGenInputs['StartSessionInput']; // StartSessionInput!
    }
    updatePomodoroPrefs: { // args
      input: NexusGenInputs['UpdatePomodoroPrefsInput']; // UpdatePomodoroPrefsInput!
    }
    updateTasksCompletedSessions: { // args
      input: NexusGenInputs['UpdateTasksCompletedSessionsInput']; // UpdateTasksCompletedSessionsInput!
    }
    updateTasksCompletion: { // args
      input: NexusGenInputs['UpdateTasksCompletionInput']; // UpdateTasksCompletionInput!
    }
  }
  Query: {
    tasksByProjectId: { // args
      project_id: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: GraphQLContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}